# serverless.yml
appEnv: ${env.APP_ENV}
distributionId: ${env.DISTRIBUTION_ID}
hush:
  component: '@sls-next/serverless-component@3.6.0'
  inputs:
    name:
      defaultLambda: "hush-it-${appEnv}-front-default"
      imageLambda: "hush-it-${appEnv}-front-image"
    bucketRegion: 'ap-northeast-2'
    bucketName: 'hush-it-${appEnv}-front-static'
    cloudfront:
      distributionId: "${distributionId}"
